export type {
  TraceProvider,
  ToolCategory,
  SyntheticKind,
  TraceEventKind,
  TraceEvent,
  BaseEvent,
  UserMessageEvent,
  SyntheticMessageEvent,
  AssistantMessageEvent,
  ReasoningEvent,
  ToolCallEvent,
  ToolResultEvent,
  SystemEvent,
  ErrorEvent,
  CompactionEvent,
  FileChangeEvent,
  TurnBoundaryEvent,
  UnknownEvent,
  TraceUsage,
  RunStats,
  TimelineSpan,
  TraceRun,
  SessionSummary,
  FileChangeSummary,
  StructuredPatch,
} from '../../src/core/schema.js';
